// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActions(arg1) {
  return window['go']['controller']['actionController']['GetActions'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['controller']['actionController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['actionController']['OnStartup'](arg1);
}
