// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRun(arg1) {
  return window['go']['controller']['jobController']['CancelRun'](arg1);
}

export function CreateJob(arg1) {
  return window['go']['controller']['jobController']['CreateJob'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['controller']['jobController']['DeleteJob'](arg1);
}

export function GetJob(arg1) {
  return window['go']['controller']['jobController']['GetJob'](arg1);
}

export function GetRun(arg1) {
  return window['go']['controller']['jobController']['GetRun'](arg1);
}

export function GetRunOutput(arg1) {
  return window['go']['controller']['jobController']['GetRunOutput'](arg1);
}

export function ListJobs() {
  return window['go']['controller']['jobController']['ListJobs']();
}

export function ListRunsByJob(arg1) {
  return window['go']['controller']['jobController']['ListRunsByJob'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['controller']['jobController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['jobController']['OnStartup'](arg1);
}

export function RunJob(arg1) {
  return window['go']['controller']['jobController']['RunJob'](arg1);
}

export function UpdateJob(arg1) {
  return window['go']['controller']['jobController']['UpdateJob'](arg1);
}
