// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {context} from '../models';

export function CreateJobGroup(arg1:dto.CreateJobGroupRequest):Promise<dto.JobGroupResponse>;

export function DeleteJobGroup(arg1:string):Promise<void>;

export function ListJobGroupsByWorkspace(arg1:string):Promise<Array<dto.JobGroupResponse>>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function UpdateJobGroup(arg1:dto.UpdateJobGroupRequest):Promise<dto.JobGroupResponse>;
