// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateJobGroup(arg1) {
  return window['go']['controller']['jobGroupController']['CreateJobGroup'](arg1);
}

export function DeleteJobGroup(arg1) {
  return window['go']['controller']['jobGroupController']['DeleteJobGroup'](arg1);
}

export function ListJobGroupsByWorkspace(arg1) {
  return window['go']['controller']['jobGroupController']['ListJobGroupsByWorkspace'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['controller']['jobGroupController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['jobGroupController']['OnStartup'](arg1);
}

export function UpdateJobGroup(arg1) {
  return window['go']['controller']['jobGroupController']['UpdateJobGroup'](arg1);
}
