// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSession(arg1) {
  return window['go']['controller']['sessionController']['CreateSession'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['controller']['sessionController']['DeleteSession'](arg1);
}

export function GetSession(arg1) {
  return window['go']['controller']['sessionController']['GetSession'](arg1);
}

export function ListSessions() {
  return window['go']['controller']['sessionController']['ListSessions']();
}

export function ListSessionsByRepo(arg1) {
  return window['go']['controller']['sessionController']['ListSessionsByRepo'](arg1);
}

export function ListSessionsByTask(arg1) {
  return window['go']['controller']['sessionController']['ListSessionsByTask'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['controller']['sessionController']['OnShutdown'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['controller']['sessionController']['OnStartup'](arg1);
}

export function ResumeSession(arg1) {
  return window['go']['controller']['sessionController']['ResumeSession'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['controller']['sessionController']['SendMessage'](arg1, arg2);
}

export function StartSession(arg1) {
  return window['go']['controller']['sessionController']['StartSession'](arg1);
}

export function StopSession(arg1) {
  return window['go']['controller']['sessionController']['StopSession'](arg1);
}
